version: "3.7"

services:
  django:
    image: murrengan/wi_fi_open_data_core:latest
    command: gunicorn core.wsgi:application --bind 0.0.0.0:8000
    env_file:
      - .env
    depends_on:
      - db
    expose:
      - 8000
    volumes:
      - static_volume:/home/wi_fi_open_data_api/staticfiles
  db:
    image: postgres:11
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres_user
      - POSTGRES_PASSWORD=postgres_password
      - POSTGRES_DB=postgres_bd
  nginx:
    image: nginx:mainline-alpine
    ports:
      - 80:80
    volumes:
      - static_volume:/home/wi_fi_open_data_api/staticfiles
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - django

volumes:
  postgres_data:
  static_volume:
