# Generated by Django 3.2.4 on 2021-06-03 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WiFiSpot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.IntegerField()),
                ('name', models.CharField(max_length=100)),
                ('adm_aria', models.CharField(max_length=100)),
                ('district', models.CharField(max_length=50)),
                ('park_name', models.CharField(max_length=200)),
                ('wi_fi_name', models.CharField(max_length=50)),
                ('coverage_area', models.IntegerField()),
                ('function_flag', models.CharField(max_length=50)),
                ('access_flag', models.CharField(max_length=50)),
                ('longitude_WGS84', models.FloatField()),
                ('latitude_WGS84', models.FloatField()),
            ],
            options={
                'verbose_name': 'Точка доступа Wi-fi',
                'verbose_name_plural': 'Точки доступа Wi-fi',
            },
        ),
    ]
